### ISSUE TITLE
Enable officers to edit their divisions

### ISSUE THREAD

**Issue by razzun** [razzun/vvarsc#5]
Allow senior officers to edit the divisions they command by reassigning units as needed.

**Comment by ech0whiskey** [comment]
Commit: 0d8da1316dcae921e3de7898b057ce85fcb52036 [0d8da13]
Parents: 14f6cd5f5a
Author: Eric Weinerman <eric.weinerman@prolifiq.com>
Date: Friday, September 16, 2016 12:04:34 PM
Labels: HEAD, origin/New_master, New_master
added ability for Officers to manage their own unit, and allowing officers of parent units to manage children as well!
