### ISSUE TITLE
Image resources use absolute path http://vvarmachine.com/uploads/galleries/

### ISSUE THREAD

**Issue by adoormouse** [razzun/vvarsc#8]
Description:
 Some Images resources from vvarsc use absolute path to http://vvarmachine.com/uploads/galleries/.  This should be moved locally and referenced as a relative path which is domain independent.

`<img class="filter_header_arrow" align="center" src="http://vvarmachine.com/uploads/galleries/SC_Button01.png">`

Image Resources:
- http://vvarmachine.com/uploads/galleries/SC_background_pic_02.png
- http://vvarmachine.com/uploads/galleries/SC_Button01.png

Affected Pages:
- inc/header.php 
- units.php 
- shipyard.php 
- admin/admin_qualifications.php 
- player.php 
- mission.php 
- operation.php

Result:
  vvarmachine.com hosts resources in `/galleries` and carries the burden for this traffic for any clones of vvarsc site.

Resolution:
  Relocate image resources "/galleries" at site's root and use relative path.
`<img class="filter_header_arrow" align="center" src="/galleries/SC_Button01.png">`

http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

**Comment by razzun** [comment]
This is being tracked in Trello.  Closing here.
